### ISSUE TITLE
Too much bottom margin bottom

### ISSUE THREAD

**Issue by Angelk90** [cawfree/react-dark-mode-toggle#12]
Hi @cawfree , 
I congratulate you on the module, I'm having some problems.
As you can see from the image, there is too much distance between the component and the object below.

Would it be possible to do something to remove this margin?

Link: [codesandbox](https://codesandbox.io/s/nice-silence-7twir?file=/src/App.js)

<img width="220" alt="Schermata 2020-08-15 alle 16 07 59" src="https://user-images.githubusercontent.com/20476002/90314173-008f0600-df12-11ea-913d-ceacbcf603f0.png">

**Comment by cawfree** [comment]
Can you trying using `display: "flex"` for the container?

**Comment by Angelk90** [comment]
@cawfree , Ok, it seems to work.
Although it is strange behavior, I believe it is due to the lottie and svg file.

**Comment by cawfree** [comment]
Thanks for confirming, @Angelk90! Yes it is strange, ideally we shouldn't expect implementors to do this. Maybe the component itself is missing a `<div>` that is set to `display: "flex"`.

**Comment by Angelk90** [comment]
@cawfree , One last thing about this, using your proposed solution I have the problem that the toggle is moved from the right where it is to the left.
Now I would like it all right, but I am unable to find a solution that will fit both chrome and firefox.

I tried all kinds of align, I also tried float: right, I tried to replace the container div with a span, but nothing works.

Do you have any suggestions?

<img width="1290" alt="Schermata 2020-08-15 alle 16 56 28" src="https://user-images.githubusercontent.com/20476002/90315038-70a08a80-df18-11ea-9e3f-66db28e1ffa0.png">


```
        <AppBar position="fixed" className={classes.appBar} style={{ backgroundColor: "#ccc", boxShadow: "none" }}>
          <Toolbar className={"shadow-none"}>
            <IconButton
              color="inherit"
              aria-label="open drawer"
              edge="start"
              onClick={handleDrawerToggle}
              className={classes.menuButton}
            >
              <Menu />
            </IconButton>Menu
            <div className="flex-1 text-right flex" style={{ }}>
              <DarkModeToggle
                onChange={handleThemeChange}
                checked={darkState}
                size={60}
              />
            </div>
          </Toolbar>
        </AppBar>
```
