### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by todd-elvers** [cawfree/react-dark-mode-toggle#15]
This component looks and performs great, but does not work at all in TypeScript due to the lack of a definitions file.

I plan on making a PR to include the definitions file in the library directly, but until then TypeScript users can create a definition file (e.g. `declaration.d.ts`) in their project and paste in the following to get up and running:
```typescript
declare module "react-dark-mode-toggle" {
  import React from "react";
  declare type Props = {
    size?: number | string;
    checked?: boolean;
    onChange?: (isChecked: boolean) => void;
    speed?: number;
    className?: string;
  };
  declare const _default: React.MemoExoticComponent<(props: Props) => JSX.Element>;
  export default _default;
}
```

**Comment by cawfree** [comment]
@todd-elvers This would be great. Please feel free to send over the PR and I'll happy get this published. Apologies for the delay in getting back to you!

**Comment by todd-elvers** [comment]
PR available [here](https://github.com/cawfree/react-dark-mode-toggle/pull/16).  This issue can be closed after that is merged.

**Comment by cawfree** [comment]
#16

**Comment by cawfree** [comment]
[**0.2.0**](https://www.npmjs.com/package/react-dark-mode-toggle/v/0.2.0)
