### ISSUE TITLE
Interaction bug

### ISSUE THREAD

**Issue by Joaolfelicio** [cawfree/react-dark-mode-toggle#3]
Hello @cawfree hope that you can help me here, I'm using **tsx** and every time I interact with the nav bar (where the dark mode toggle is), by clicking on any of the links or writing in the search box, the position of the toggle changes.
Im using mobX to manage the state of the dark mode.

Seems like a bug, correct me if I'm wrong. Attached you will find a gif of the "bug".
You can also check the code [here](https://github.com/Joaolfelicio/programming-lines/blob/master/client-app/src/features/nav/NavBar.tsx)

![darkToggle](https://user-images.githubusercontent.com/44256600/81867977-d411c980-9571-11ea-91fd-45b21858cfbe.gif)

Thanks a lot and great work on the awesome component!
Joao Felicio

**Comment by cawfree** [comment]
Hey there! Glad it has helped you out. :) Sorry to hear that's causing you some trouble.

So, really strange. It seems to me like the state is constantly changing? Like, as if it was being remounted or something like that? Or the `checked` state keeps changing?

It's hard to say without any code. Have you tried printing out the state of the toggle whenever one of these interactions happen? Does it happen to change or anything like that? I'll spin up a quick example and see if I can replicate it.

**Comment by cawfree** [comment]
Wow! I can replicate it like so:

```javascript
import React, {useState} from "react";
import DarkModeToggle from "react-dark-mode-toggle";

export default () => {
  const [isDarkMode, setIsDarkMode] = useState(() => false);
  const [text, setText] = useState('');
  return (
    <div
    >
      <input
        onChange={({ target: { value } }) => setText(value)}
        value={text}
      />
      <DarkModeToggle
        onChange={setIsDarkMode}
        checked={isDarkMode}
        size={80}
      />
    </div>
  );
};
```

Absolutely crazy. Let me look into it.

**Comment by Joaolfelicio** [comment]
Thanks for the fast reply!

Do you think it's because of the deprecated life cycles in Lottie?

**Comment by cawfree** [comment]
I didn't know there _were_ deprecated cycles! To be honest, the whole interface with the animation felt like a hack. You get much finer control in React Native, where I spent most of my time, so the whole approach I've taken here might not be great. I'm trying a couple of superficial things just to sense check the layout, but do you have any references to the deprecated functionality?

**Comment by cawfree** [comment]
Okay, think I've fixed it. I'll just make a PR and republish and see how you get on.

**Comment by Joaolfelicio** [comment]
That's awesome, thank you a lot!

Best regards

**Comment by cawfree** [comment]
:) Hope this works for you!

**Comment by Joaolfelicio** [comment]
I confirm that is working on my side.
Thank you once again!

**Comment by cawfree** [comment]
Awesome. Thank you for raising! Best of luck!

**Comment by Angelk90** [comment]
Hi @cawfree , i am having the same problem as @Joaolfelicio, i am using latest version 0.0.9.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20476002/90313761-65952c80-df0f-11ea-8c8c-eb977412e943.gif)

**Comment by cawfree** [comment]
Hey @Angelk90, thanks for letting us know!

Would it be possible for you to provide us with a minimum
reproducible example?

Many thanks!

**Comment by Angelk90** [comment]
@cawfree , certainly the problem seems to be due when they share the same state.

Try to write some text continuously in the input field, as you can see the toggle changes.

Example:
https://codesandbox.io/s/nice-silence-7twir?file=/src/App.js

**Comment by cawfree** [comment]
Thanks for this. It's really strange that it does this.

I'll keep this issue open so we can work on a fix, however in the mean time I think we can prevent excessive re-renders by using the `useCallback` hook.

Example:
https://codesandbox.io/s/elastic-dream-3ck3p?file=/src/App.js

**Comment by Angelk90** [comment]
@cawfree , In the example I don't see any use of useCallback hook.

**Comment by cawfree** [comment]
Sorry I originally pasted the wrong URL; can you try again?

```javascript
import React, { useState, useCallback } from "react";
import DarkModeToggle from "react-dark-mode-toggle";

export default () => {
  const [state, setState] = useState({
    darkState: false,
    text: ""
  });
  const { darkState, text } = state;

  const setIsDarkMode = useCallback(
    () => setState((prev) => ({ ...prev, darkState: !prev.darkState })),
    []
  );

  return (
    <div>
      <div style={{ backgroundColor: "#accaac" }}>
        <input
          onChange={({ target: { value } }) =>
            setState((prev) => ({ ...prev, text: value }))
          }
          value={text}
        />
      </div>
      <div style={{ backgroundColor: "#ccc" }}>
        <DarkModeToggle
          onChange={setIsDarkMode}
          checked={darkState}
          size={80}
        />
      </div>
      <input
        onChange={({ target: { value } }) =>
          setState((prev) => ({ ...prev, text: value }))
        }
        value={text}
      />
    </div>
  );
};
```

**Comment by Angelk90** [comment]
@cawfree , 
I'm trying to figure out what the problem may be.
By analyzing a little the situation of the component it can be seen that:

1) As soon as the component is mounted, there are two initial changes in the component, so the whole changes twice.
We can say normal.

2) When the component is toggled, the component there are several changes, many we can say.
I don't know if this is normal behavior.

3) When the toggle is on the Sun state, and only one letter is inserted into the input field, then change the state.
The component is updated 4 times.

4) When the toggle is in the Night state, and only one letter is inserted into the input field, then change the state.
The component is updated 2 times.

They seem like weird behaviors.


You can see everything in the browser console.
Link: https://codesandbox.io/s/nice-silence-7twir?file=/src/App.js

**Comment by Daidalos117** [comment]
I got very similar strange behavior. For example toggle checked on, even when passing false to checked at render. 
I solved it by wrapping whole component to memo, like so.
`const MemoizedToggle = memo(DarkModeToggle);
...
<MemoizedToggle onChange={toggleTheme} .. \>`
Seems to work now just fine.

**Comment by todd-elvers** [comment]
I ran into this issue too and the problem seems to be related to re-renders.  The simple workaround is to restrict how/when the component decides to re-render using `React.memo`.  For example this is my toggle:

```ts
 export const Toggle = React.memo(() => {
     const { colorScheme, setColorScheme } = Theme.useColorScheme();

     return (
       <DarkModeToggle
         onChange={() =>
           setColorScheme(colorScheme === "dark" ? "light" : "dark")
         }
         checked={colorScheme === "dark"}
         size={85}
       />
     );
   }
 );
```

@Angelk90 here's your example w/ the workaround applied:
https://codesandbox.io/s/gracious-lichterman-eex53?file=/src/App.js

**Comment by cawfree** [comment]
Hey everyone, apologies for neglecting this repository for a while.

@Angelk90 
Is this still a problem that persists? I was unable to replicate on the supplied url.

@todd-elvers
Correct! Generally speaking, we should only be rendering the component when we wish for it to change state. In your example, as your component grows in complexity using `React.useMemo` will only serve as a fix for the short term, since you'll still be reallocting a new `onChange` function every time. One adjustment I'd be inclined to make is:

```javascript
 export const Toggle = () => {
     const { colorScheme, setColorScheme } = Theme.useColorScheme();
     const isDark = colorScheme === "dark";
     const onChangeColorScheme = React.useCallback(() => {
       setColorScheme(isDark ? "light" : "dark");
     }, [isDark, setColorScheme]);

     return (
       <DarkModeToggle
         onChange={onChangeColorScheme}
         checked={isDark}
         size={85}
       />
     );
   }
```

**Comment by todd-elvers** [comment]
@cawfree Thank you, that is indeed a better solution as it addresses the heart of the issue.

**Comment by cawfree** [comment]
#16

**Comment by cawfree** [comment]
[**0.2.0**](https://www.npmjs.com/package/react-dark-mode-toggle/v/0.2.0)
