### ISSUE TITLE
[Bug] Behaves weirdly as a child of Transition component (React-Transition-Group)

### ISSUE THREAD

**Issue by krharsh17** [cawfree/react-dark-mode-toggle#4]
I have used this button in my blog (https://blog.krharsh17.vision) and it works absolutely fine as a static element on the homepage. However, while trying to put it in a collapsible navbar in one of the pages, it started automatically changing its state. I've used a Transition component, inside of it, there's another div and finally, inside this div, there is this button. I am animating the navbar out of the page when the user scrolls down, and back in when the user scrolls up. Here's the code for the top navbar:

```

const TopNav = (props) => {
    return(
    <Transition in={animate} timeout={1000}>
                {(state) => (
                    <NavContainer state={state}>
                        <NavBrand href={'/'}>brand-name</NavBrand>
                        {props.title}
                            <DarkModeToggle
                                onChange={props.toggleDarkMode}
                                checked={props.darkMode}
                                size={56}
                            />
                     </NavContainer>
                )}
    </Transition>
    );
}

```

`NavContainer` is a styled div element, while NavBrand is a styled a element. Upon scrolling up and down the page a number of times, the button changes from light to dark automatically gradually.

Here's a GIF about what exactly is happening on scroll
![ezgif-7-1c8069a5d898](https://user-images.githubusercontent.com/46624829/81869917-7fcb1180-9592-11ea-9490-55892d5d0ef9.gif)

**Comment by cawfree** [comment]
Looks like #3. Can you please update to [0.0.4](https://github.com/cawfree/react-dark-mode-toggle/commit/3747f06eb27af855e2b5c2fdca9a2b5a1a615839) and see how you get on?

By the way, your timing couldn't be better. The same issue got raised in the past 30 minutes!

**Comment by krharsh17** [comment]
Alright, updating. Thanks for the quick reply though 😅

**Comment by krharsh17** [comment]
Yup, fixed 🙌 Awesome work 👏

**Comment by cawfree** [comment]
Great news! Thanks @krharsh17!
