### ISSUE TITLE
Disable animation when dark mode default is true

### ISSUE THREAD

**Issue by tianenpang** [cawfree/react-dark-mode-toggle#8]
Hello @cawfree 

I set the dark mode is true, and the animation will be executed again every time the page refreshes or reloads.

Is there get some functions to not repeat the animation when the dark mode is true by default?
 
Just like the dark mode is false, render and display toggle directly.

![dark](https://user-images.githubusercontent.com/32772271/86530533-0f82a180-beec-11ea-93f1-5852e008929a.gif)

**Comment by cawfree** [comment]
Hey @TianenPang, thanks for getting in touch.

Originally I thought it would be cool to actually see the initial animation on mount, but given your example I agree that the user experience isn’t great.

This should be easy enough to implement, we just have to set the proper initialValue of the animation when mounted, based on the state.

Would you like to submit a PR? It should be just a one line change! I’m slightly busy for the next couple of days, but if you’re happy to wait I can fix this for you.

**Comment by tianenpang** [comment]
Hi @cawfree 

I would like to submit a PR, but I tried many times and didn't find which one is the animation initialValue.

I tried to control the `progress` but the animation will be pause or loop, still not understand how it working.

Please fix this issue when you free or please tell me which attribute is to control the animation that i can try again.

It's really cool to see the animation after loading, but in some scenes feel a little unsuitable, and i think the better way is not to directly cancel the animation after page loading, but use attributes to control whether to show the default animation after page loading, that wiil be adapt to many situations. 

like `disableDarkInitialAnimation = true`

Thank you.👍

**Comment by cawfree** [comment]
Hey @TianenPang, sorry for the delay in getting back to you. I'll take a look at implementing this now.

Thank you for your patience!

**Comment by tianenpang** [comment]
Thank you @cawfree , take your time.😊

**Comment by cawfree** [comment]
Hey @TianenPang, I've rolled out this improvement in version [0.0.7](https://www.npmjs.com/package/react-dark-mode-toggle/v/0.0.7).

So, it was a bit more in depth than I imagined. Apologies for misleading you with the progress.

The workaround I've used is to force time to progress once mounted. The caveat to this is that you can briefly see the first frame of the animation. To work around this, I've added a short fade to the component upon mount.

On the bright side, by specifying the initial animation offset manually, we can animate _slightly_ on load to show the night time effect. :)

**Comment by tianenpang** [comment]
Cool @cawfree 

Thanks again for this awesome component 👍
